---

- hosts: all
  become: true
  tasks:

  - name: disable selinux
    selinux: 
      state: disabled
    notify:
      - system restart
  
  - name: Устанавливаем epel-репозиторий
    yum:
      name: epel-release
      state: present
    tags:
      - epel-package
      - packages

  - name: Устанавливаем необходимые и вспомогательные пакеты через yum
    yum:
      name: "{{item}}"
      state: present
    loop:
      - mc
      - nano
      - net-tools
      - yum-utils
      - bind-utils
      - tcpdump
      - traceroute        
      - net-tools
      - iotop
      - elinks

  - name: Обозначаем ip_forward
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes

  - name: Ставим фильтр общий rp_filter
    sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: 0
      sysctl_set: yes
      state: present
      reload: yes

  - name: Ставим фильтр на eth1 rp_filter
    sysctl:
      name: net.ipv4.conf.eth1.rp_filter
      value: 0
      sysctl_set: yes
      state: present
      reload: yes

  - name: Ставим фильтр на eth2 rp_filter
    sysctl:
      name: net.ipv4.conf.eth2.rp_filter
      value: 0
      sysctl_set: yes
      state: present
      reload: yes
    
  handlers:    
  - name: system restart
    reboot: 
        reboot_timeout: 100   
    
